### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by macka601** [sandain/MinecraftServerControlScript#100]
Hi,
Using your software for my daughters server, it's been great! However, just making sure i stay on top of version numbers etc.. so is it possible to put a command in for script version number? prehaps? even a self-update?

Thanks

**Comment by zanix** [comment]
There really isn't a version number for the script, the closest thing to that would be the git commit hash.
You can see the commit log here https://github.com/sandain/MinecraftServerControlScript/commits/master

**Comment by sandain** [comment]
Sorry about my lack of reply, I've been on vacation.  Zanix is right, I don't really feel it is necessary to maintain a version number.  The git commit hash would be the closest thing that you could use.  It would be relatively simple to add an upgrade command to the Makefile however, I'll put some thought into how best to do that.

This is essentially what I do for upgrades currently: `git pull && sudo make update`.

**Comment by sandain** [comment]
Closing this as won't fix.  I'll create a stable branch every once and a while with a version number (date) attached to the name of the branch.  I'll backport fixes to those stable branches as needed.

I don't see a need to add an update command to the Makefile since updates are so simple.
