### ISSUE TITLE
systemd not working

### ISSUE THREAD

**Issue by conrad784** [sandain/MinecraftServerControlScript#101]
Hi,
at first I want to say I love your script, saved me a lot of time.

But unfortunately the systemd startup does not work. I'm on a Debian 8 (jessie) machine.

"systemctl status mscs.service" gives me this: 
● mscs.service - Minecraft Server Control Script
   Loaded: loaded (/lib/systemd/system/mscs.service; enabled)
   Active: failed (Result: exit-code) since Wed 2015-11-04 16:42:23 CET; 15s ago
     Docs: https://github.com/sandain/MinecraftServerControlScript
  Process: 2696 ExecStart=/usr/local/bin/mscs start (code=exited, status=203/EXEC)
 Main PID: 2696 (code=exited, status=203/EXEC)

It's not really an issue, but it would be neat if it worked.
Thanks.

**Comment by conrad784** [comment]
my bad, mscs can be found in /usr/bin --> it can't work

**Comment by zanix** [comment]
Not sure what you are getting at...
Does the script not work on Debian 8?
Is it just the systemd script?

**Comment by sandain** [comment]
Hi @conrad784.  If you use the Makefile to install the script, I think it should be working.  I'm confused about your last message.  The script should be placed in `/usr/local/bin` which is where the `mscs.service` file tells systemd to find the script.  If you used the Makefile to install everything and you are still having issues, then there might be a bug somewhere that we need to track down.  I'm currently at work, but I'll try to spend some time looking over things when I get home tonight.

**Comment by conrad784** [comment]
I installed it manually.
https://github.com/sandain/MinecraftServerControlScript#configuration says /usr/bin

I resolved the issue by editing this in the mscs.service file, now it works

**Comment by sandain** [comment]
I just fixed the locations in the README file with commit 6cf7c96d3ae0e1d20704c94b0491615ce4750700.  Sorry about not updating the documentation when the file locations changed!

**Comment by conrad784** [comment]
no problem
but as a Linux newbie, why should I change the location from /usr/bin to /usr/local/bin?

**Comment by sandain** [comment]
Ok, with my latest commit 4c5694911f7e2cb9c441604fd024d34d1523a70c, I think the README and the Makefile are in agreement.

The `/usr/bin` directory is usually only for system tools, while `/usr/local/bin` is for user installed programs.  It doesn't really mater in the grand scheme of things.

**Comment by conrad784** [comment]
as it is a dedicated vServer only for Minecraft it should not cause any trouble for anybody, thanks!

**Comment by sandain** [comment]
Sorry for the trouble!  I remember asking @jjchico to update the documentation when he sent in the patches that made these changes, but it appears I accepted the patches without any documentation updates.  I'll audit the README and wiki pages when I get home to make sure that everything else is current.
