### ISSUE TITLE
How to use the msctl script

### ISSUE THREAD

**Issue by sandain** [sandain/MinecraftServerControlScript#102]
There is currently no documentation on how to use the `msctl` script, just the `mscs` script.

**Comment by Roflicide** [comment]
Is this covered by the recent updates to the README or no?

**Comment by sandain** [comment]
No.  The `msctl` script can be configured to work for multiple users on the same system, with each user able to control their own servers but not servers controlled by others.  So, for example lets say I had a user account on my server named `sandain`, if I were to use the `msctl` script the world files would be stored in `/home/sandain/mscs/worlds` instead of the global location `/opt/mscs/worlds`.  User `bob` on my server could independently run servers out of his home directory `/home/bob/mscs/worlds`, and neither would conflict with servers run by the `minecraft` user in `/opt/mscs/worlds`.  All users still have to coordinate which ports are being used, but @jjchico solved the permissions problems to make this possible.

The `mscs` script is now simply a wrapper for the `msctl` script that sets up the `minecraft` user to be used, so most of the documentation is exactly the same for the two scripts.
