### ISSUE TITLE
Make Install seems to fail

### ISSUE THREAD

**Issue by zanix** [sandain/MinecraftServerControlScript#103]
On a fresh Ubuntu 14.04 install running `make install` seems to fail.
Looking at the make file, it seems that it's designed for systemd.

This is the output I see
```
$ make install
install -m 0755 msctl /usr/local/bin/msctl
install -m 0755 mscs /usr/local/bin/mscs
install -m 0644 mscs.completion /etc/bash_completion.d/mscs
if which systemctl; then \
                install -m 0644 mscs.service /etc/systemd/system/mscs.service; \
        fi
adduser --system --group --home /opt/mscs --quiet minecraft
if which systemctl; then \
                systemctl -f enable mscs.service; \
        fi
```
I had to manually link `/usr/local/bin/mscs` to `/etc/init.d/mscs` and run `update-rc.d mscs defaults`

Is another makefile needed or do we need to say that systems not using systemd need to install manually? Did I mis-read the install instructions?

**Comment by zanix** [comment]
Looks good to me, I'll test when I have the chance.

**Comment by zanix** [comment]
Probably should also add the removal of the link and `update-rc.d mscs remove` or whatever the command is supposed to be under `clean`.

**Comment by sandain** [comment]
Ohh, good point.  Here is a patch with the `clean` target:

```
@@ -3,6 +3,7 @@ MSCS_HOME := /opt/mscs
 
 MSCTL := /usr/local/bin/msctl
 MSCS := /usr/local/bin/mscs
+MSCS_INIT_D := /etc/init.d/mscs
 MSCS_SERVICE := /etc/systemd/system/mscs.service
 MSCS_COMPLETION := /etc/bash_completion.d/mscs
 
@@ -12,6 +13,9 @@ install: update
 	adduser --system --group --home $(MSCS_HOME) --quiet $(MSCS_USER)
 	if which systemctl; then \
 		systemctl -f enable mscs.service; \
+	else \
+		ln -s $(MSCS) $(MSCS_INIT_D); \
+		update-rc.d mscs defaults; \
 	fi
 
 update:
@@ -26,5 +30,7 @@ clean:
 	if which systemctl; then \
 		systemctl -f disable mscs.service; \
 		rm -f $(MSCS_SERVICE); \
+	else \
+		update-rc.d mscs remove; \
 	fi
 	rm -f $(MSCTL) $(MSCS) $(MSCS_SERVICE) $(MSCS_COMPLETION)
@sandain
Commit changes
```

**Comment by zanix** [comment]
You will want to also add `$(MSCS_INIT_D);` to the `rm -f` line

**Comment by sandain** [comment]
I caught that right after I clicked comment.  I just edited the above post.

**Comment by zanix** [comment]
I'll try to work up a code pull later tonight

**Comment by sandain** [comment]
I can probably just import the patch right now without testing.  It looks good to me.

**Comment by sandain** [comment]
I went ahead and pushed commit 8191fab5f2e8e2b32195454fceb18de9b51f1f9b.  Let me know if you have any problems with installation now.

I'll close this, but if it still doesn't work, feel free to reopen.
