### ISSUE TITLE
Port this to LGSM ?

### ISSUE THREAD

**Issue by UltimateByte** [sandain/MinecraftServerControlScript#105]
Hi there,

I was thinking about adding Minecraft support to LGSM which is a kind of unified game server manager for linux.
https://github.com/dgibbs64/linuxgsm/issues/333
Would you be interested in working together to port your script to LGSM ? That would probably be tough but awesome !
Otherwise i'll just start from scratch. :)

**Comment by sandain** [comment]
What does LGSM need to operate?  I imagine it would be pretty easy to implement whatever happens to be missing.

**Comment by UltimateByte** [comment]
Well, LGSM has a bunch of premade functions helping to locate useful files and directories, service names, launching the process into a tmux session and that kind of stuff. It's made to be as user friendly as possible, and to share a maximum of functions with other similar games.
So it would consist in adapting your script to fit inside LGSM functions, and probably add some missing ones. I personally start to know LGSM pretty well, at least well enough to implement a new game (already did Hurtworld support), so i guess it's doable, especially if we're doing this together.
Do you feel like doing it ?

**Comment by sandain** [comment]
i was just looking through some of the source code, and it looks like there would be a lot of duplicate functionality if mscs was included in LGSM as-is, it might make more sense to just steal code from mscs to create a new script for LGSM.

for example: the LGSM start command (https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_start.sh) functionally duplicates the code found in the start() method of this script.  While LGSM utilizes tmux to hold the console's screen, mscs uses a set of UNIX pipes/files (console.in and console.out) to avoid the unneeded dependency on tmux (or GNU screen).

I am simply too busy right now to write a new script, but I would be happy to provide advice if this is something you want to tackle on your own.  Feel free to steal code from this script (with attribution please) if it helps.

**Comment by UltimateByte** [comment]
Well, that sounds perfect to me !
I don't know when i'll start this but i just wanted to know if it would be at least possible to work together or to get some help if needed.
I'll keep you informed. Be sure to get some credits if we use some of your work. :)

**Comment by sandain** [comment]
There is too much overlap for MSCS to be merged into LGSM.  For LGSM to gain support for Minecraft, a new script (which could be loosely based on code in MSCS) will need to be written.  Since this does not affect MSCS at all, I'm going to close this issue.
