### ISSUE TITLE
Symlink Client Location for Overviewer

### ISSUE THREAD

**Issue by zanix** [sandain/MinecraftServerControlScript#108]
Have the make file create a symlink so we don't have to specify the texture path in the `overviewer-settings.py` file

If we symlink `/opt/mscs/.minecraft/versions` to `/opt/mscs/client/` then Overviewer will be able to find the default Minecraft textures to render maps.

**Comment by zanix** [comment]
This also has the added benefit of not having to manually update the texture path in `overviewer-settings.py` when the server is updated to a new version.

**Comment by sandain** [comment]
I'll accept a patch that you have tested if you have one.  Otherwise, I'll play around with Overviewer sometime this week and get a patch together.

**Comment by zanix** [comment]
That's right, I forgot that the client jars were only meant for Overviewer. Since they are only used for mapping, it would make sense to put them where Overviewer expects them.
Overviewer specifically looks for the client jar in the current user's home directory, so more specifically the correct path is `~/.minecraft/versions/`

I do need to do some testing with snapshots, Overviewer might not use this "default" texture path and may require this setting to have a value.

I may also have a better default overviewer-settings file, that includes the Nether and The End.

**Comment by sandain** [comment]
I just sent commit 56950b7e12fcb145ae3812b61e4f4460e08d3c1a that moves the client location to the normal location and removes the setting from the `overviewer-settings.py` file.  If you have a better default `overviewer-settings.py`, I'll take a patch or create one if you let me know what it is.

**Comment by sandain** [comment]
Oops, I didn't mean to close the issue with that comment.

**Comment by zanix** [comment]
Will do

**Comment by zanix** [comment]
I think we can call this one closed and open another issue for a different overviewer default file.
