### ISSUE TITLE
Error running mscs status

### ISSUE THREAD

**Issue by zanix** [sandain/MinecraftServerControlScript#109]
```
Minecraft Server Status:
  server1: running version 1.8.9 (0 of 20 users online).
    Process ID: 6238.
  server2: /usr/local/bin/msctl: 1730: printf: 127.0.1.1: not completely converted
running version 48 (25566 of 127 users online).
```
Looks like the port number is in the response

**Comment by sandain** [comment]
Hmm, not sure what is going on here.  Can you post a copy of the mscs.properties file?  Is there an error in it?

**Comment by zanix** [comment]
I don't think they have an error in them as they start, run, and stop just fine.

My config is a bit long because of the custom command for java parameters, I can try to remove them later and test again. The weird thing is that it's the same file copied from server2 to server1.

server1:
```
mscs-enabled=true
mscs-server-command=$JAVA -Xms$INITIAL_MEMORY -Xmx$MAXIMUM_MEMORY -XX\:PermSize\=256m -XX\:NewRatio\=3 -XX\:SurvivorRatio\=3 -XX\:TargetSurvivorRatio\=80 -XX\:MaxTenuringThreshold\=8 -XX\:+UseParNewGC -XX\:+UseConcMarkSweepGC -XX\:MaxGCPauseMillis\=10 -XX\:GCPauseIntervalMillis\=50 -XX\:MaxGCMinorPauseMillis\=7 -XX\:+ExplicitGCInvokesConcurrent -XX\:+UseCMSInitiatingOccupancyOnly -XX\:CMSInitiatingOccupancyFraction\=60 -XX\:+BindGCTaskThreadsToCPUs -Xnoclassgc -jar $SERVER_LOCATION/$SERVER_JAR $SERVER_ARGS
```

server2:
```
mscs-enabled=true
mscs-server-command=$JAVA -Xms$INITIAL_MEMORY -Xmx$MAXIMUM_MEMORY -XX\:PermSize\=256m -XX\:NewRatio\=3 -XX\:SurvivorRatio\=3 -XX\:TargetSurvivorRatio\=80 -XX\:MaxTenuringThreshold\=8 -XX\:+UseParNewGC -XX\:+UseConcMarkSweepGC -XX\:MaxGCPauseMillis\=10 -XX\:GCPauseIntervalMillis\=50 -XX\:MaxGCMinorPauseMillis\=7 -XX\:+ExplicitGCInvokesConcurrent -XX\:+UseCMSInitiatingOccupancyOnly -XX\:CMSInitiatingOccupancyFraction\=60 -XX\:+BindGCTaskThreadsToCPUs -Xnoclassgc -jar $SERVER_LOCATION/$SERVER_JAR $SERVER_ARGS
```

**Comment by sandain** [comment]
Maybe it is in the server.properties file?  I don't know.  You could also check the `query.in` and `query.out` files.

**Comment by zanix** [comment]
The query.in/out files are binary, should I stop the server and delete them?

server.properties
```
#Minecraft server properties
#Sat Jan 23 16:58:50 MST 2016
spawn-protection=16
max-tick-time=60000
query.port=25566
server-name=Snapshot
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=false
enable-query=true
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
announce-player-achievements=true
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=false
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25566
server-ip=
spawn-npcs=true
allow-flight=false
level-name=snapshot
view-distance=10
resource-pack=
spawn-animals=true
white-list=true
generate-structures=true
max-build-height=256
online-mode=true
level-seed=
use-native-transport=true
enable-rcon=false
motd=Welcome to \u00A76\u00A7lSnapshot\u00A7r\u00A7r\nCheck out the new stuff
```

**Comment by zanix** [comment]
Stopped the server, removed the `mscs-server-command` from `mscs.properties`, deleted `query.in/out` and restarted. `mscs status` still shows the same error.

I think that this is being returned from the query for some reason
```
127.0.1.1: not completely converted
running version 48
```

**Comment by sandain** [comment]
I might need to see the query.in and query.out files.  There is something weird going on, and I might need to add code to work around it.  You can use a hex editor to see the content of those files.

**Comment by zanix** [comment]
query.in/out look ok to me

https://owncloud.redstonelabs.net/index.php/s/j6T6B1aIdnjJ7Vz
https://owncloud.redstonelabs.net/index.php/s/zcnCTcNHjawYzbR

**Comment by Roflicide** [comment]
After a rather uneventful super bowl I decided to look into this issue more... 4 hours of investigation and I _think_ I've found the cause

When I ran using your `server.properties`, I got the error you described above. So I commented out each of the lines and eventually narrowed it down to your MOTD--when I removed your MOTD, the server query worked fine. After narrowing every character on the MOTD itself, its actually the newline escape character you have. If you remove the `\n` part from your MOTD, it should work--it worked for me.

So your MOTD right now is:
    
    motd=Welcome to \u00A76\u00A7lSnapshot\u00A7r\u00A7r\nCheck out the new stuff
    
Remove the `\n':
    
    motd=Welcome to \u00A76\u00A7lSnapshot\u00A7r\u00A7r\Check out the new stuff
    
& it should work.

However, where my testing differs from what you described above is that it didn't matter whether I was on the snapshot version or 1.8--it gave me the same error regardless if I had a newline character in the file. The issue you described above is where one server worked but another one didn't, and I simply could not replicate that for both versions--I got an error for both.

@sandain Any ideas on this?

**Comment by zanix** [comment]
Weird, I removed the new-line character from the motd and it works. I had to restart the world first, so that tells me the new-line character in `server.properties` is not the issue, but the query response from a world with a motd with a new-line character is most likely the cause.

Here is a list of all the sequences and characters allowed in the motd http://minecraft.gamepedia.com/Formatting_codes#Use_in_server.properties_and_pack.mcmeta

**Comment by Roflicide** [comment]
> the query response from a world with a motd with a new-line character is most likely the cause.
Yes, I agree with this.

However, it doesn't make sense to me what you were describing above: that one world was fine whereas the other was returning the bad response despite both having new-line characters. 

@zanix When I tested this, anytime I placed a new-line character--regardless of the minecraft world or version--it gave me that bad response. **Are you absolutely sure** that what you described above is true--that one world still works even though it has a new-line character in the MOTD? Because I can't seem to replicate that scenario.

**Comment by sandain** [comment]
I'm sure the issue is in the `querySendPacket` method, starting about [here](https://github.com/sandain/MinecraftServerControlScript/blob/master/msctl#L1580).  Now that @Roflicide  has done the hard work of narrowing down the issue, maybe I can spend some time trying to come up with a solution.  It probably has something to do with Perl automatically splitting the incoming query stream on `\n`.

**Comment by sandain** [comment]
I'm writing from my tablet, so I can't test anything yet.  However, my guess is that we need to change line 1580 to `RESPONSE=$($PERL -ne -0 0777 '`, or something similar anyway...

**Comment by zanix** [comment]
> However, it doesn't make sense to me what you were describing above: that one world was fine whereas the other was returning the bad response despite both having new-line characters

Looking at my previous comments and provided files it seems that I copied the wrong server files for server1.
the MOTD line for that server should have been
```ini
motd=The \u00A7cREMOVED \u00A7eFamily \u00A79Hangout
```

Indeed every server that I enter "\n" in the MOTD gives the bad response.

> I'm writing from my tablet, so I can't test anything yet. However, my guess is that we need to change line 1580 to `RESPONSE=$($PERL -ne -0 0777 '`, or something similar anyway...

That does not seem to work
```
Can't open
      $hex .= sprintf "%.2x", $_ foreach (unpack "C*", $_);
      $hex =~ s/^0*0900000001/0900000001/;
      print $hex;
    : No such file or directory.
```

The second suggestion results in the script thinking the servers are offline
```
Minecraft Server Status:
  server1: running (query server offline).
    Process ID: 4948.
  snapshot: running (query server offline).
    Process ID: 9251.
  server2: running (query server offline).
    Process ID: 12277.
```

**Comment by sandain** [comment]
Well shoot, I thought that was a pretty good bet.  I'll keep thinking, and maybe I'll have time to play around with some options when I get home tonight.

**Comment by Roflicide** [comment]
> Looking at my previous comments and provided files it seems that I copied the wrong server files for server1.
> Indeed every server that I enter "\n" in the MOTD gives the bad response.

Ahh okay, that makes sense now. Then it's definitely the `\n`

**Comment by sandain** [comment]
I just posted a patch that should fix this problem.  It was a little more involved than I expected.  Here is the commit: 12668fe908946365c2682b8772c3a7924c699504.

**Comment by zanix** [comment]
I'll try this soon.

**Comment by zanix** [comment]
Looks like that fixed it
