### ISSUE TITLE
server libraries conflict

### ISSUE THREAD

**Issue by tobyjoiner** [sandain/MinecraftServerControlScript#68]
It's me again the forge pain in the butt lol.  I am trying to run forge 1.6.4 and forge 1.7.10 on the same server and the libraries directory is going to get over written.  maybe there needs to be sub directories for each server jar to make sure there is no overwriting of the previous "libraries" directory?

**Comment by zanix** [comment]
Makes sense, the original Pull request #43 for Forge support did specify library paths and added them to the start server command. It almost looks like it put the libraries in each world rather than alongside the server jar. I think that placing the server jar in it's own subdir may be a good way to solve this.

**Comment by sandain** [comment]
What exactly is the problem?  The libraries should have version tags on the file names, so conflicts should not happen as far as I can tell.  I just tried running three different versions simultaneously with no issue:
```
cd /opt/mscs/server/

wget http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.6.4-9.11.1.1345/forge-1.6.4-9.11.1.1345-installer.jar
wget http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1451-1.7.10/forge-1.7.10-10.13.4.1451-1.7.10-installer.jar
wget http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.8-11.14.3.1450/forge-1.8-11.14.3.1450-installer.jar

java -jar forge-1.6.4-9.11.1.1345-installer.jar --installServer
java -jar forge-1.7.10-10.13.4.1451-1.7.10-installer.jar --installServer
java -jar forge-1.8-11.14.3.1450-installer.jar --installServer

mscs create forge-1.6.4 25569
mscs create forge-1.7.10 25570
mscs create forge-1.8 25571

nano /opt/mscs/worlds/forge-1.7.10/eula.txt
nano /opt/mscs/worlds/forge-1.8/eula.txt

mscs start
mscs status
```
Here is a composite status report:
```
Minecraft Server Status:
  forge-1.6.4: running version 1.6.4 (1 of 20 users online).
    Players: sandain.
    Process ID: 10458.
  forge-1.7.10: running version 1.7.10 (1 of 20 users online).
    Players: sandain.
    Process ID: 12542.
  forge-1.8: running version 1.8 (1 of 20 users online).
    Players: sandain.
    Process ID: 17113.
```

**Comment by zanix** [comment]
I didn't notice that the library files had version number too. @sandain is right, this should not be a problem.

**Comment by tobyjoiner** [comment]
I am sorry, I didn't check that either.  I just assumed it would cause issues.  Thank you again!
