### ISSUE TITLE
Systemd can't find script in default installation

### ISSUE THREAD

**Issue by CoiLock** [sandain/MinecraftServerControlScript#95]
After installing with the supplied Makefile the systemd service can't start because it references to /usr/bin/mscs but the script is located at /usr/local/bin/mscs

**Comment by jjchico** [comment]
Hi!

May you try the fix at branch [systemd-fix](https://github.com/jjchico/MinecraftServerControlScript/tree/systemd-fix)?

It also changes service file installation to /etc/systemd/system. Please remove '/lib/systemd/system/mscs.service' an test it.

Thanks.

**Comment by CoiLock** [comment]
Thank you!

It works now.

**Comment by sandain** [comment]
Reopening.  The fixes are not yet upstream.

**Comment by sandain** [comment]
I went ahead and merged your systemd-fix branch.  Thanks for taking care of this fix.
